In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle

In [2]:
# NOW Lets our model and all the pickle file

model = load_model('ann_model.h5')

# Load the scaler
with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

# Load the label encoder
with open('le_gender.pkl', 'rb') as file:
    le_gender = pickle.load(file)

# Load the ohe encoder

with open('ohe_geo.pkl', 'rb') as file:
    ohe_geo = pickle.load(file)


In [3]:
input_data = {
    "CreditScore": 650,
    "Geography": "France",
    "Gender":"Female",
    "Age": 30,
    "Tenure": 2,
    "Balance": 60000,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 50000

}

In [5]:
geo_encd = ohe_geo.transform([[input_data['Geography']]]).toarray()
geo_encd


c:\Users\nzqt1\Desktop\annClassification\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [6]:
geo_encoded= pd.DataFrame(geo_encd, columns=ohe_geo.get_feature_names_out(['Geography']))

In [8]:
# Convert input_data dictionary to DataFrame and concatenate with geo_encoded
input_data = pd.DataFrame([input_data])
input_data = pd.concat([input_data, geo_encoded], axis=1)
input_data = input_data.drop('Geography', axis=1)

In [9]:
input_data

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          650  Female   30       2    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [10]:
input_data.Gender= le_gender.transform(input_data.Gender)

In [11]:
input_data

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          650       0   30       2    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [12]:
scaled_input_data = scaler.transform(input_data)

In [13]:
scaled_input_data

array([[-0.01709861, -1.09499335, -0.84593077, -1.04241787, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [14]:
prediction = model.predict(scaled_input_data)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step


array([[0.01785815]], dtype=float32)

In [15]:
if prediction[0][0] > 0.5:
    print("The customer is likely to leave the bank.")
else:
    print("The customer is likely to stay with the bank.")

The customer is likely to stay with the bank.
